const fake = [
    {
        id: 1,
        name: "Taj Mahal",
        img: "https://i.postimg.cc/P5TM2Kvw/Background-1.png",
        description: "The Taj Mahal 'Crown of the Palace' is an ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan  to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself",
        cost: 75000,
        transportation: "Bus or Airplane",
    },
    {
        id: 2,
        name: "Eiffel Tower",
        img: "https://i.postimg.cc/XJSKB8Wq/Background-2.png",
        description: "The Eiffel Tower grows to 330 meters tall! With the installation of a new digital terrestrial radio antenna by TDF, the Tower will grow by 6 meters (20 feet).",
        cost: 800000,
        transportation: " Airplane",
    },
    {
        id: 3,
        name: "Mount Everest",
        img: "https://i.postimg.cc/2y83Jbmr/Background-3.png",
        description: "Mount Everest is Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. The China Nepal border runs across its summit point.Its elevation of 8,848.86 m (29,031.7 ft) was most recently established in 2020 by the Chinese and Nepali authorities.",
        cost: 255000,
        transportation: " Airplane",
    },
    {
        id: 4,
        name: "London Bridge",
        img: "https://i.postimg.cc/N0GdbtPT/Background-4.png",
        description: "Tower Bridge is a Grade I listed combined bascule and suspension bridge in London, built between 1886 and 1894, designed by Horace Jones and engineered by John Wolfe Barry with the help of Henry Marc Brunel.[1] The bridge crosses the River Thames close to the Tower of London and is one of five London bridges owned and maintained by the Bridge House Estates, a charitable trust founded in 1282. The bridge was constructed to give better access to the East End of London, which had expanded its commercial potential in the 19th century. The bridge was opened by Edward, Prince of Wales and Alexandra, Princess of Wales in 1894.",
        cost: 800000,
        transportation: "Airplane",
    },
    {
        id: 5,
        name: "Sahara Desert",
        img: "https://i.postimg.cc/nhLXFwsZ/Background-5.png",
        description: "The Sahara  is a desert on the African continent. With an area of 9,200,000 square kilometres (3,600,000 sq mi), it is the largest hot desert in the world and the third largest desert overall, smaller only than the deserts of Antarctica and the northern Arctic.",
        cost: 500000,
        transportation: " Airplane",
    },
    {
        id: 6,
        name: "Istanbul",
        img: "https://i.postimg.cc/05TGNSDr/Background.png",
        description: "Istanbul is a major city in Turkey that straddles Europe and Asia across the Bosphorus Strait. Its Old City reflects cultural influences of the many empires that once ruled here. In the Sultanahmet district, the open-air, Roman-era Hippodrome was for centuries the site of chariot races, and Egyptian obelisks also remain. The iconic Byzantine Hagia Sophia features a soaring 6th-century dome and rare Christian mosaics",
        cost: 250000,
        transportation: " Airplane",
    },
    {
        id: 7,
        name: "Dubai",
        img: "https://i.postimg.cc/NMGJpHpQ/Background9.png",
        description: "Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline. At its foot lies Dubai Fountain, with jets and lights choreographed to music. On artificial islands just offshore is Atlantis, The Palm, a resort with water and marine-animal parks.",
        cost: 30000,
        transportation: " Airplane",
    },

]